repos:
- repo: local
  hooks:
    - id: black
      name: black
      entry: black
      args: [--line-length=120,  --enable-unstable-feature=string_processing, --preview]
      language: python
      types: [python]

